name: Windows Server 2022

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2022
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
    - name: Checkout lavi
      uses: actions/checkout@v3
      with:
        path: 'lavi'
        submodules: 'recursive'

    - name: Cache CMake build
      uses: actions/cache@v3
      with:
        path: |
          lavi/build
          lavi/build/CMakeFiles
        key: build-cache-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
        restore-keys: |
          build-cache-${{ runner.os }}-
    - name: Configure CMake for lavi
      run: cmake -DCMAKE_BUILD_TYPE=Release -B build .
      working-directory: lavi

    - name: Build project for lavi
      run: cmake --build build --config Release --parallel
      working-directory: lavi

    - name: Install lavi
      run: cmake --install build --config Release
      working-directory: lavi

    - name: Configure lavi again so the installer can find it
      run: cmake -DCMAKE_BUILD_TYPE=Release -B build .
      working-directory: lavi

    - name: Build the installer
      run: cmake --build build --config Release --parallel --target lavi-installer
      working-directory: lavi

    - name: Generate artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lavi-artifacts
        path: |
          lavi/build/Release/lavi.exe
          lavi/build/Release/lavi-installer.exe
    - name: Run tests for lavi
      run: |
        & "C:\Program Files (x86)\lavi\bin\lavi.exe" --tests
      working-directory: lavi