name: Windows Server 2022

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2022
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
    - name: Checkout andy-lang
      uses: actions/checkout@v3
      with:
        path: 'andy-lang'
        submodules: 'recursive'

    - name: Cache CMake build
      uses: actions/cache@v3
      with:
        path: |
          andy-lang/build
          andy-lang/build/CMakeFiles
        key: build-cache-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
        restore-keys: |
          build-cache-${{ runner.os }}-
    - name: Configure CMake for andy-lang
      run: cmake -DCMAKE_BUILD_TYPE=Release -B build .
      working-directory: andy-lang

    - name: Build project for andy-lang
      run: cmake --build build --config Release --parallel
      working-directory: andy-lang

    - name: Install andy-lang
      run: cmake --install build --config Release
      working-directory: andy-lang

    - name: Configure andy again so the installer can find it
      run: cmake -DCMAKE_BUILD_TYPE=Release -B build .
      working-directory: andy-lang

    - name: Build the installer
      run: cmake --build build --config Release --parallel --target andy-lang-installer
      working-directory: andy-lang

    - name: Generate artifacts
      uses: actions/upload-artifact@v4
      with:
        name: andy-artifacts
        path: |
          andy-lang/build/Release/andy.exe
          andy-lang/build/Release/andy-lang-installer.exe
    - name: Run tests for andy-lang
      run: |
        & "C:\Program Files (x86)\andy-lang\bin\andy.exe" --tests
      working-directory: andy-lang