name: Ubuntu 22.04

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y build-essential

    - name: Checkout lavi
      uses: actions/checkout@v3
      with:
        path: 'lavi'
        submodules: 'recursive'

    - name: Configure CMake for lavi
      run: cmake -DCMAKE_BUILD_TYPE=Release -B build .
      working-directory: lavi
      
    - name: Build project for lavi
      run: cmake --build build --config Release --parallel
      working-directory: lavi

    - name: Install lavi
      run: sudo cmake --install build --config Release
      working-directory: lavi

    - name: Check lavi version
      run: lavi --version
      working-directory: lavi

    - name: Run tests for lavi
      run: lavi --tests
      working-directory: lavi

    - name: Generate artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          lavi/build/lavi
          lavi/build/lavi-analyzer